ROOT = ../../../../..

include ${ROOT}/rules/defs.mk
LIBBASES = align cluster distancemat distancemat_merops options sequence tree util

LIBFILE = ${sonlib_lib}
CFLAGS_INCL += -I${sonlib_incldir} -I../include



include ${ROOT}/rules/rules.mk
